### ISSUE TITLE
SSH connection user

### ISSUE THREAD

**Issue by ghost** [obreitwi/asfa#6]
How do you specify a different user to login via SSH as?

**Comment by obreitwi** [comment]
A different user can be specified by `user`. Unfortunately, the example config is missing that information right now, good catch!

But the config I use for CI does have a custom user set, see [HERE](https://github.com/obreitwi/asfa/blob/fa906cdad068ab214ea7830f0be22deb7c19d583/test-utils/ci-config/raw.yaml).
