### ISSUE TITLE
Default expiry in config file

### ISSUE THREAD

**Issue by matclab** [obreitwi/asfa#8]
It would be nice to be able to set a default expiry time in the config file.

Thanks for this nice piece of software

**Comment by obreitwi** [comment]
That is a very good suggestion, I'll get on it as soon as I find the time! :+1:

**Comment by obreitwi** [comment]
Added in 29a1c9cdea90e872e63397418fc34851b341f3a5.

**Comment by matclab** [comment]
Just tried it and it works like a charm.
Thank you very much !
